# Personal packages take precedence over the official extra repository.
[raf]
SigLevel = PackageRequired TrustedOnly DatabaseOptional
Server = https://github.com/rozeraf/raf-repo/releases/download/$arch
