color0 #474747
color1 #ffb4ab
color2 #e7b4ff
color3 #d3c0d8
color4 #f4b7b7
color5 #e7b4ff
color6 #d3c0d8
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #e7b4ff
color11 #d3c0d8
color12 #f4b7b7
color13 #e7b4ff
color14 #d3c0d8
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #e7b4ff
inactive_border_color #474747
url_color             #e7b4ff

active_tab_foreground   #491765
active_tab_background   #e7b4ff
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
