# Font
font_family JetBrains Mono Nerd Font
font_size 11.0

# Cursor
cursor_shape beam
cursor_trail 1

# Padding
window_margin_width 21.75

# No close confirmation
confirm_os_window_close 0

# Shell
shell zsh

# Shell integration
shell_integration yes

# Remote control for custom scripts/kittens
allow_remote_control yes

# Mod key
kitty_mod ctrl+shift

# Theme
include current-theme.conf

# Background
background_opacity 0.88
background_blur 1
dynamic_background_opacity yes

# Copy or interrupt
map ctrl+c copy_or_interrupt
map ctrl+с copy_or_interrupt

# Copy to clipboard
map kitty_mod+c copy_to_clipboard
map kitty_mod+с copy_to_clipboard

# Paste from clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+м paste_from_clipboard

# New OS window
# n -> т
map kitty_mod+n new_os_window
map kitty_mod+т new_os_window

# New tab
# t -> е
map kitty_mod+t new_tab
map kitty_mod+е new_tab

# Close window
# w -> ц
map kitty_mod+w close_window
map kitty_mod+ц close_window

# Next layout
# l -> д
map kitty_mod+l next_layout
map kitty_mod+д next_layout

# Unicode input
# u -> г
map kitty_mod+u kitten unicode_input
map kitty_mod+г kitten unicode_input

# Open URL hints
# e -> у
map kitty_mod+e open_url_with_hints
map kitty_mod+у open_url_with_hints

# Search
# f -> а
map ctrl+f launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
map ctrl+а launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
map kitty_mod+f launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
map kitty_mod+а launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

# Scroll
map page_up scroll_page_up
map page_down scroll_page_down

# Font size up
map ctrl+plus change_font_size all +1
map ctrl+equal change_font_size all +1
map ctrl+kp_add change_font_size all +1

# Font size down
map ctrl+minus change_font_size all -1
map ctrl+underscore change_font_size all -1
map ctrl+kp_subtract change_font_size all -1

# Reset font size
map ctrl+0 change_font_size all 0
map ctrl+kp_0 change_font_size all 0

# Custom clipboard script
# y -> н
map super+y launch --type=background sh -lc '~/.local/bin/kitty_copy_clipboard.sh'
map super+н launch --type=background sh -lc '~/.local/bin/kitty_copy_clipboard.sh'
