config_version = 13

[bar]
order = [ "default", "bar" ]

    [bar.bar]
    center = [ "workspaces" ]
    enabled = true
    end = []
    margin_ends = 450
    position = "left"
    reserve_space = false
    smart_auto_hide = true
    start = []

    [bar.default]
    enabled = true
    end = [ "tray", "keyboard_layout", "volume", "battery", "session" ]
    margin_ends = 0
    start = [ "launcher", "widget", "media" ]

        [bar.default.dead_zone.actions]
        scroll_down = "volume-down 2"
        scroll_up = "volume-up 2"

    [bar.widgets]
    center = []
    enabled = false
    end = []
    start = []

[plugins]
enabled = [ "alexander/screen-toolkit" ]

[shell]
clipboard_auto_paste = "off"

    [shell.launcher]
    auto_paste = "off"

[theme]
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "niri", "starship" ]
    community_ids = [ "zen-browser", "zed", "fastfetch", "yazi" ]

[wallpaper]
directory = "~/Pictures/Wallpapers"

[widget.keyboard_layout]
show_glyph = false

[widget.notifications]
anchor = true

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.widget]
type = "alexander/screen-toolkit:widget"
