node.filter-graph.rules = [
    {
        matches = [
            {
                "node.name" = "alsa_output.usb-C-Media_Electronics_Inc_MCHOSE_V9_PRO_0123456789AB-01.analog-stereo"
            }
        ]

        actions = {
            create-filter-graph = [
                {
                    nodes = [
                        {
                            type = builtin
                            name = eq
                            label = param_eq
                            config = {
                                filename = "/home/raf/.config/pipewire/bass-eq.txt"
                            }
                        }
                    ]

                    inputs = [
                        "eq:In 1"
                        "eq:In 2"
                    ]

                    outputs = [
                        "eq:Out 1"
                        "eq:Out 2"
                    ]
                }
            ]
        }
    }
]
