node.filter-graph.rules = [
    {
        matches = [
            {
                "node.name" = "alsa_output.usb-C-Media_Electronics_Inc_MCHOSE_V9_PRO_0123456789AB-01.analog-stereo"
            }
        ]

        actions = {
            create-filter-graph = [
                {
                    nodes = [
                        {
                            type = builtin
                            name = eq
                            label = param_eq
                            config = {
                                filters = [
                                    {
                                        type = bq_lowshelf
                                        freq = 80.0
                                        gain = 7.0
                                        q = 0.707
                                    }
                                ]
                            }
                        }
                        {
                            type = builtin
                            name = preamp_left
                            label = linear
                            control = {
                                "Mult" = 0.316227766
                                "Add" = 0.0
                            }
                        }
                        {
                            type = builtin
                            name = preamp_right
                            label = linear
                            control = {
                                "Mult" = 0.316227766
                                "Add" = 0.0
                            }
                        }
                    ]

                    links = [
                        { output = "eq:Out 1" input = "preamp_left:In" }
                        { output = "eq:Out 2" input = "preamp_right:In" }
                    ]

                    inputs = [
                        "eq:In 1"
                        "eq:In 2"
                    ]

                    outputs = [
                        "preamp_left:Out"
                        "preamp_right:Out"
                    ]
                }
            ]
        }
    }
]
